// File generated by Gochart version "{{.Version}}" at {{.Time}}
// DO NOT MODIFY!

#include "{{.HeaderInclude}}"

#include <cassert>

// TODO(cdc): This is very simple, but something fancier to support more compilers could be needed.
#ifdef _MSC_VER
#define GOCHART_DEBUG_BREAK __debugbreak()
#else
#define GOCHART_DEBUG_BREAK ___builtin_debugtrap()
#endif

namespace gochart
{


void {{.ImplName}}:::Activate()
{
    assert(!CurrentState.IsValid());
}

void {{.ImplName}}::Deactivate()
{
    assert(CurrentState.IsValid());
}

void {{.ImplName}}::EnterState(State state, State* route, std::size_t route_size)
{
    state.PerformEnterReactions();
    CurrentState = state;
}

const char* {{.ImplName}}::ToString(States state)
{
	switch (state) {
		{{- range .Statechart.States }}
		case States::{{.Name}}: return "{{.Name}}";
		{{- end }}
		case States::None: return "None";
	}

	GOCHART_DEBUG_BREAK;
	return "<invalid>";
}

{{.ImplName}}::States {{.ImplName}}::ParentState(States state)
{
  // clang-format off
	switch (state) {
		{{- range .Statechart.States }}
		case States::{{.Name}}: return {{if .Parent}}States::{{.Parent.Name}}{{else}}States::None{{end}};
		{{- end }}
		case States::None: GOCHART_DEBUG_BREAK; return States::None;
	}
  // clang-format on
}

// {{.ImplName}}::State ----------------------------------------------------------------------------

} // namespace gochart

#undef GOCHART_DEBUG_BREAK
